COMP: Fix module logic build adding missing semi colon
This commit fixes the following error:

  /path/to/MarginCalculator/MotionSimulator/Logic/vtkSlicerMotionSimulatorModuleLogic.cxx:295:5: error: expected ‘;’ before ‘return’
    295 |     return -1;
        |     ^~~~~~